import type { ReportDefinition } from "./types";

// Every projection is explicit so schema additions can never leak into reports.
export const REPORTS: Readonly<Record<string, ReportDefinition>> = {
  "current-stock": { name:"current-stock", title:"Current Stock Report", companyColumn:"b.company_id", sql:"SELECT c.code company,sb.name stock_book,i.code item_code,i.name item,i.unit,b.quantity_milliunits,b.fifo_value_paise,i.minimum_stock_milliunits,CASE WHEN b.quantity_milliunits<=0 THEN 'OUT' WHEN b.quantity_milliunits<i.minimum_stock_milliunits THEN 'LOW' ELSE 'OK' END status,b.item_id id FROM inventory_balances b JOIN companies c ON c.id=b.company_id JOIN stock_books sb ON sb.id=b.stock_book_id JOIN items i ON i.id=b.item_id WHERE 1=1" },
  "fifo-valuation": { name:"fifo-valuation", title:"FIFO Valuation Report", companyColumn:"f.company_id", dateColumn:"f.source_date", sql:"SELECT c.code company,sb.name stock_book,i.code item_code,i.name item,SUM(f.available_quantity_milliunits) quantity_milliunits,SUM(f.available_value_paise) fifo_value_paise,MAX(f.source_date) date,MAX(f.id) id FROM fifo_layers f JOIN companies c ON c.id=f.company_id JOIN stock_books sb ON sb.id=f.stock_book_id JOIN items i ON i.id=f.item_id WHERE f.available_quantity_milliunits>0" },
  "fifo-layers": { name:"fifo-layers", title:"FIFO Layer Detail", companyColumn:"f.company_id", dateColumn:"f.source_date", sql:"SELECT c.code company,sb.name stock_book,i.code item_code,i.name item,f.source_type,f.source_reference,f.source_date date,f.original_quantity_milliunits,f.available_quantity_milliunits,f.unit_cost_ten_thousandths,f.available_value_paise,f.status,f.id FROM fifo_layers f JOIN companies c ON c.id=f.company_id JOIN stock_books sb ON sb.id=f.stock_book_id JOIN items i ON i.id=f.item_id WHERE 1=1" },
  "stock-ledger": { name:"stock-ledger", title:"Stock Ledger", companyColumn:"l.company_id", dateColumn:"l.entry_date", sql:"SELECT l.entry_date date,c.code company,sb.name stock_book,i.code item_code,i.name item,l.movement_type,l.transaction_type,l.reference_number,l.quantity_in_milliunits,l.quantity_out_milliunits,l.rate_ten_thousandths,l.value_paise,l.remarks,l.id FROM stock_ledger_entries l JOIN companies c ON c.id=l.company_id JOIN stock_books sb ON sb.id=l.stock_book_id JOIN items i ON i.id=l.item_id WHERE 1=1" },
  "purchases": { name:"purchases", title:"Purchase Report", companyColumn:"p.company_id", dateColumn:"p.bill_date", sql:"SELECT p.bill_date date,c.code company,s.name supplier,p.bill_number,p.purchase_type,p.subtotal_paise,p.gst_total_paise,p.grand_total_paise,p.paid_amount_paise,p.balance_amount_paise,p.payment_status,p.id FROM purchases p JOIN companies c ON c.id=p.company_id JOIN suppliers s ON s.id=p.supplier_id WHERE p.is_void=0" },
  "purchases-monthly": { name:"purchases-monthly", title:"Monthly Purchase Report", companyColumn:"p.company_id", dateColumn:"p.bill_date", sql:"SELECT substr(p.bill_date,1,7) month,c.code company,COUNT(p.id) document_count,SUM(p.subtotal_paise) subtotal_paise,SUM(p.gst_total_paise) gst_total_paise,SUM(p.grand_total_paise) grand_total_paise,MAX(p.bill_date) date,MAX(p.id) id FROM purchases p JOIN companies c ON c.id=p.company_id WHERE p.is_void=0" },
  "sales": { name:"sales", title:"Sales Report", companyColumn:"s.company_id", dateColumn:"s.invoice_date", sql:"SELECT s.invoice_date date,c.code company,cu.name customer,s.invoice_number,s.sale_type,s.subtotal_paise,s.gst_total_paise,s.grand_total_paise,s.fifo_cost_paise,s.gross_profit_paise,s.balance_amount_paise,s.payment_status,s.id FROM sales s JOIN companies c ON c.id=s.company_id JOIN customers cu ON cu.id=s.customer_id WHERE s.is_void=0" },
  "sales-monthly": { name:"sales-monthly", title:"Monthly Sales Report", companyColumn:"s.company_id", dateColumn:"s.invoice_date", sql:"SELECT substr(s.invoice_date,1,7) month,c.code company,COUNT(s.id) document_count,SUM(s.subtotal_paise) subtotal_paise,SUM(s.gst_total_paise) gst_total_paise,SUM(s.grand_total_paise) grand_total_paise,SUM(s.gross_profit_paise) gross_profit_paise,MAX(s.invoice_date) date,MAX(s.id) id FROM sales s JOIN companies c ON c.id=s.company_id WHERE s.is_void=0" },
  "sales-by-type": { name:"sales-by-type", title:"Sales by Company and Type", companyColumn:"s.company_id", dateColumn:"s.invoice_date", sql:"SELECT c.code company,s.sale_type,COUNT(s.id) document_count,SUM(s.grand_total_paise) grand_total_paise,SUM(s.gross_profit_paise) gross_profit_paise,MAX(s.invoice_date) date,MAX(s.id) id FROM sales s JOIN companies c ON c.id=s.company_id WHERE s.is_void=0" },
  "gross-profit": { name:"gross-profit", title:"Gross Profit Report", companyColumn:"s.company_id", dateColumn:"s.invoice_date", sql:"SELECT s.invoice_date date,c.code company,s.invoice_number,cu.name customer,s.grand_total_paise,s.fifo_cost_paise,s.gross_profit_paise,CASE WHEN s.subtotal_paise=0 THEN 0 ELSE (s.gross_profit_paise*10000)/s.subtotal_paise END margin_basis_points,s.id FROM sales s JOIN companies c ON c.id=s.company_id JOIN customers cu ON cu.id=s.customer_id WHERE s.is_void=0" },
  "customer-outstanding": { name:"customer-outstanding", title:"Customer Outstanding", companyColumn:"r.company_id", dateColumn:"r.document_date", sql:"SELECT c.code company,cu.code customer_code,cu.name customer,COUNT(r.id) document_count,SUM(r.total_amount_paise) total_amount_paise,SUM(r.paid_amount_paise) paid_amount_paise,SUM(r.balance_amount_paise) balance_amount_paise,MIN(r.due_date) earliest_due,MAX(r.document_date) date,MAX(r.id) id FROM receivables r JOIN companies c ON c.id=r.company_id JOIN customers cu ON cu.id=r.customer_id WHERE r.balance_amount_paise>0" },
  "supplier-outstanding": { name:"supplier-outstanding", title:"Supplier Outstanding", companyColumn:"p.company_id", dateColumn:"p.document_date", sql:"SELECT c.code company,s.code supplier_code,s.name supplier,COUNT(p.id) document_count,SUM(p.total_amount_paise) total_amount_paise,SUM(p.paid_amount_paise) paid_amount_paise,SUM(p.balance_amount_paise) balance_amount_paise,MIN(p.due_date) earliest_due,MAX(p.document_date) date,MAX(p.id) id FROM payables p JOIN companies c ON c.id=p.company_id JOIN suppliers s ON s.id=p.supplier_id WHERE p.balance_amount_paise>0" },
  "advances": { name:"advances", title:"Advances Received/Paid", companyColumn:"p.company_id", dateColumn:"p.payment_date", sql:"SELECT p.payment_date date,c.code company,p.party_type,COALESCE(cu.name,s.name) party,p.payment_type,p.reference_number,p.total_amount_paise,p.allocated_amount_paise,p.unallocated_amount_paise,p.id FROM payments p JOIN companies c ON c.id=p.company_id LEFT JOIN customers cu ON cu.id=p.customer_id LEFT JOIN suppliers s ON s.id=p.supplier_id WHERE p.unallocated_amount_paise>0" },
  "payment-history": { name:"payment-history", title:"Payment History", companyColumn:"p.company_id", dateColumn:"p.payment_date", sql:"SELECT p.payment_date date,c.code company,p.party_type,COALESCE(cu.name,s.name) party,p.payment_type,p.mode,p.reference_number,p.total_amount_paise,p.allocated_amount_paise,p.unallocated_amount_paise,p.id FROM payments p JOIN companies c ON c.id=p.company_id LEFT JOIN customers cu ON cu.id=p.customer_id LEFT JOIN suppliers s ON s.id=p.supplier_id WHERE 1=1" },
  "due-alerts": { name:"due-alerts", title:"Due and Overdue Report", companyColumn:"x.company_id", dateColumn:"x.document_date", sql:"SELECT x.document_date date,x.company,x.party_type,x.party,x.document_number,x.due_date,x.balance_amount_paise,x.days_due,x.id FROM (SELECT r.company_id,c.code company,'CUSTOMER' party_type,cu.name party,r.document_number,r.document_date,r.due_date,r.balance_amount_paise,CAST(julianday('now')-julianday(r.due_date) AS INTEGER) days_due,r.id FROM receivables r JOIN companies c ON c.id=r.company_id JOIN customers cu ON cu.id=r.customer_id WHERE r.balance_amount_paise>0 UNION ALL SELECT p.company_id,c.code,'SUPPLIER',s.name,p.document_number,p.document_date,p.due_date,p.balance_amount_paise,CAST(julianday('now')-julianday(p.due_date) AS INTEGER),p.id FROM payables p JOIN companies c ON c.id=p.company_id JOIN suppliers s ON s.id=p.supplier_id WHERE p.balance_amount_paise>0) x WHERE 1=1" },
  "stock-alerts": { name:"stock-alerts", title:"Low Stock and Stock-Out Report", companyColumn:"b.company_id", sql:"SELECT c.code company,sb.name stock_book,i.code item_code,i.name item,b.quantity_milliunits,i.minimum_stock_milliunits,CASE WHEN b.quantity_milliunits<=0 THEN 'OUT' ELSE 'LOW' END status,b.item_id id FROM inventory_balances b JOIN companies c ON c.id=b.company_id JOIN stock_books sb ON sb.id=b.stock_book_id JOIN items i ON i.id=b.item_id WHERE b.quantity_milliunits<=i.minimum_stock_milliunits" },
  "inter-company": { name:"inter-company", title:"Inter-Company Usage and Balance", companyColumn:"l.stock_owner_company_id", dateColumn:"t.transfer_date", sql:"SELECT t.transfer_date date,oc.code owner_company,uc.code user_company,t.reference_number,i.code item_code,l.quantity_milliunits,l.amount_owed_paise,l.settled_amount_paise,l.balance_amount_paise,l.status,l.due_date,l.id FROM inter_company_ledger_entries l JOIN inter_company_transfers t ON t.id=l.transfer_id JOIN companies oc ON oc.id=l.stock_owner_company_id JOIN companies uc ON uc.id=l.stock_user_company_id LEFT JOIN items i ON i.id=l.item_id WHERE 1=1" },
  "opening-summary": { name:"opening-summary", title:"Opening Balance Summary", companyColumn:"x.company_id", dateColumn:"x.date", sql:"SELECT x.date,x.company,x.kind,x.reference,x.amount_paise,x.quantity_milliunits,x.id FROM (SELECT o.company_id,c.code company,o.opening_date date,'STOCK' kind,o.reference_number reference,SUM(l.value_paise) amount_paise,SUM(l.quantity_milliunits) quantity_milliunits,o.id FROM opening_stocks o JOIN companies c ON c.id=o.company_id JOIN opening_stock_lines l ON l.opening_stock_id=o.id WHERE o.is_void=0 GROUP BY o.id UNION ALL SELECT r.company_id,c.code,r.document_date,'RECEIVABLE',r.document_number,r.total_amount_paise,0,r.id FROM receivables r JOIN companies c ON c.id=r.company_id WHERE r.is_opening=1 UNION ALL SELECT p.company_id,c.code,p.document_date,'PAYABLE',p.document_number,p.total_amount_paise,0,p.id FROM payables p JOIN companies c ON c.id=p.company_id WHERE p.is_opening=1) x WHERE 1=1" },
  "purchase-price-fluctuation": { name:"purchase-price-fluctuation", title:"Purchase Price Fluctuation", companyColumn:"p.company_id", dateColumn:"p.bill_date", sql:"SELECT p.bill_date date,c.code company,i.code item_code,i.name item,p.bill_number,l.rate_ten_thousandths,LAG(l.rate_ten_thousandths) OVER(PARTITION BY p.company_id,l.item_id ORDER BY p.bill_date,p.id,l.id) previous_rate_ten_thousandths,l.id FROM purchase_lines l JOIN purchases p ON p.id=l.purchase_id JOIN companies c ON c.id=p.company_id JOIN items i ON i.id=l.item_id WHERE p.is_void=0" },
  "sale-price-fluctuation": { name:"sale-price-fluctuation", title:"Sale Price Fluctuation", companyColumn:"s.company_id", dateColumn:"s.invoice_date", sql:"SELECT s.invoice_date date,c.code company,i.code item_code,i.name item,s.invoice_number,l.sale_rate_ten_thousandths,LAG(l.sale_rate_ten_thousandths) OVER(PARTITION BY s.company_id,l.item_id ORDER BY s.invoice_date,s.id,l.id) previous_rate_ten_thousandths,l.id FROM sale_lines l JOIN sales s ON s.id=l.sale_id JOIN companies c ON c.id=s.company_id JOIN items i ON i.id=l.item_id WHERE s.is_void=0" },
  "audit": { name:"audit", title:"User and Audit Report", dateColumn:"substr(a.created_at,1,10)", sql:"SELECT substr(a.created_at,1,10) date,a.created_at,u.name user_name,a.action,a.entity_type,a.entity_id,a.reference,a.approval_reason,a.id FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE 1=1" },
  "item-ledger": { name:"item-ledger", title:"Item Movement Ledger", companyColumn:"l.company_id", dateColumn:"l.entry_date", sql:"SELECT l.entry_date date,c.code company,sb.name stock_book,i.code item_code,i.name item,l.movement_type,l.transaction_type,l.reference_number,l.quantity_in_milliunits,l.quantity_out_milliunits,l.rate_ten_thousandths,l.value_paise,l.id FROM stock_ledger_entries l JOIN companies c ON c.id=l.company_id JOIN stock_books sb ON sb.id=l.stock_book_id JOIN items i ON i.id=l.item_id WHERE 1=1" },
  "customer-ledger": { name:"customer-ledger", title:"Customer Ledger", companyColumn:"x.company_id", dateColumn:"x.date", sql:"SELECT x.date,x.company,x.customer,x.kind,x.reference,x.debit_paise,x.credit_paise,x.id FROM (SELECT r.company_id,c.code company,cu.name customer,r.document_date date,r.source_type kind,r.document_number reference,r.total_amount_paise debit_paise,0 credit_paise,r.id FROM receivables r JOIN companies c ON c.id=r.company_id JOIN customers cu ON cu.id=r.customer_id UNION ALL SELECT p.company_id,c.code,cu.name,p.payment_date,'PAYMENT',COALESCE(p.reference_number,''),0,p.total_amount_paise,p.id FROM payments p JOIN companies c ON c.id=p.company_id JOIN customers cu ON cu.id=p.customer_id WHERE p.customer_id IS NOT NULL) x WHERE 1=1" }
};

export const REPORT_NAMES = Object.freeze(Object.keys(REPORTS));
