import { escapeHtml, money, qty } from "../views/html";

type Row=Record<string,unknown>;
interface SellerProfile { name:string;address:string[];gstin:string;state:string;stateCode:string;contact:string;email:string;pan:string;bankHolder:string;bankName:string;bankAccount:string;bankIfsc:string }

const LEGACY_PROFILES:Readonly<Record<string,SellerProfile>>={
  FML:{name:"FIRSTTECH MACHINE LLP",address:["Unit No. B/2, Girikunj Industrial Estate,","Near Paper Box, Off. Mahakali Caves Road,","Andheri East, Mumbai - 400093."],gstin:"27AAIFF5739P1ZO",state:"Maharashtra",stateCode:"27",contact:"022-42724058, +91 8591895162",email:"firsttechmachinellp@gmail.com",pan:"AAIFF5739P",bankHolder:"FIRSTTECH MACHINE LLP",bankName:"Kotak Mahindra Bank",bankAccount:"7647407025",bankIfsc:"Vile Parle (W), Mumbai / KKBK0000674"},
  AI:{name:"ADITYA INTERNATIONAL",address:["Jewellery factory supplies stock control"],gstin:"",state:"Maharashtra",stateCode:"27",contact:"",email:"",pan:"",bankHolder:"ADITYA INTERNATIONAL",bankName:"",bankAccount:"",bankIfsc:""},
};
const ONES=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"];
const TENS=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];
function two(value:number):string{return value<20?ONES[value]!: `${TENS[Math.floor(value/10)]} ${ONES[value%10]}`.trim();}
function numberWords(value:number):string{if(value===0)return"Zero";const parts:string[]=[];for(const [size,label] of [[10_000_000,"Crore"],[100_000,"Lakh"],[1_000,"Thousand"],[100,"Hundred"]] as const){const count=Math.floor(value/size);value%=size;if(count)parts.push(`${two(count)} ${label}`);}if(value)parts.push(two(value));return parts.join(" ");}
export function amountInWords(paise:number):string{const sign=paise<0?"Minus ":"",absolute=Math.abs(Math.trunc(paise)),rupees=Math.floor(absolute/100),remainder=absolute%100;return `${sign}INR ${numberWords(rupees)}${remainder?` and ${numberWords(remainder)} Paise`:""} Only`;}
function splitLines(value:unknown):string[]{return String(value??"").split(/\r?\n/).map(line=>line.trim()).filter(Boolean);}
function seller(company:Row):SellerProfile{const code=String(company.code??"").toUpperCase(),legacy=LEGACY_PROFILES[code];return legacy?{...legacy,gstin:String(company.gst_number||legacy.gstin)}:{name:String(company.name??code).toUpperCase(),address:[],gstin:String(company.gst_number??""),state:"",stateCode:"",contact:"",email:"",pan:"",bankHolder:String(company.name??code).toUpperCase(),bankName:"",bankAccount:"",bankIfsc:""};}
function stateCode(state:unknown):string{return String(state??"").trim().toLowerCase()==="maharashtra"?"27":"";}
function percent(basisPoints:unknown):string{return `${Number(basisPoints??0)/100}%`;}

export interface SaleInvoiceModel { document:Row;seller:SellerProfile;buyer:Row;lines:Row[];taxRows:Row[];subtotal:number;gstTotal:number;cgstTotal:number;sgstTotal:number;grandTotal:number;amountWords:string;taxWords:string;totalQuantity:number; }

export function saleInvoiceModel(document:Row,company:Row,customer:Row,sourceLines:Row[]):SaleInvoiceModel{
  const tax=new Map<string,{hsn:string;basis:number;taxable:number;tax:number}>();let totalQuantity=0;
  const lines=sourceLines.map((line,index)=>{const quantity=Number(line.quantity_milliunits??0),subtotal=Number(line.subtotal_paise??0),gst=Number(line.gst_amount_paise??0),basis=Number(line.gst_basis_points??0),hsn=String(line.hsn??"");totalQuantity+=quantity;const key=`${hsn}\0${basis}`,group=tax.get(key)??{hsn,basis,taxable:0,tax:0};group.taxable+=subtotal;group.tax+=gst;tax.set(key,group);return{...line,index:index+1,quantity_display:`${qty(quantity)} ${line.unit??"pcs"}`,rate_display:(Number(line.sale_rate_ten_thousandths??0)/10_000).toFixed(4),subtotal_display:money(subtotal)};});
  const taxRows=[...tax.values()].sort((a,b)=>a.hsn.localeCompare(b.hsn)||a.basis-b.basis).map(group=>{const cgst=Math.trunc(group.tax/2);return{hsn:group.hsn,taxable_paise:group.taxable,cgst_rate:percent(group.basis/2),cgst_amount_paise:cgst,sgst_rate:percent(group.basis-group.basis/2),sgst_amount_paise:group.tax-cgst,total_tax_paise:group.tax};});
  const gstTotal=Number(document.gst_total_paise??0),cgstTotal=Math.trunc(gstTotal/2),grandTotal=Number(document.grand_total_paise??0);
  return{document,seller:seller(company),buyer:{...customer,address_lines:splitLines(customer.address),state_code:stateCode(customer.state)},lines,taxRows,subtotal:Number(document.subtotal_paise??0),gstTotal,cgstTotal,sgstTotal:gstTotal-cgstTotal,grandTotal,amountWords:amountInWords(grandTotal),taxWords:amountInWords(gstTotal),totalQuantity};
}

export function saleInvoiceHtml(invoice:SaleInvoiceModel):string{
  const d=invoice.document,s=invoice.seller,b=invoice.buyer;
  const sellerDetails=[...s.address,s.gstin&&`GSTIN/UIN: ${s.gstin}`,s.state&&`State: ${s.state}${s.stateCode?`, Code: ${s.stateCode}`:""}`,s.contact&&`Contact: ${s.contact}`,s.email&&`E-Mail: ${s.email}`].filter(Boolean).map(value=>`<div>${escapeHtml(value)}</div>`).join("");
  const buyerDetails=[...(b.address_lines as string[]),[b.city,b.state].filter(Boolean).join(", "),b.gst_number&&`GSTIN/UIN: ${b.gst_number}`,b.state&&`State: ${b.state}${b.state_code?`, Code: ${b.state_code}`:""}`,b.mobile&&`Mobile: ${b.mobile}`].filter(Boolean).map(value=>`<div>${escapeHtml(value)}</div>`).join("");
  const lineRows=invoice.lines.map((line:any)=>[line.index,escapeHtml(`${line.code} - ${line.name}`),escapeHtml(line.hsn),escapeHtml(line.quantity_display),escapeHtml(line.rate_display),money(line.subtotal_paise),money(line.gst_amount_paise),money(line.line_total_paise)]);
  const taxRows=invoice.taxRows.map(row=>[escapeHtml(row.hsn),money(row.taxable_paise),escapeHtml(row.cgst_rate),money(row.cgst_amount_paise),escapeHtml(row.sgst_rate),money(row.sgst_amount_paise),money(row.total_tax_paise)]);
  const bank=[s.bankHolder&&`A/c holder: ${s.bankHolder}`,s.bankName&&`Bank: ${s.bankName}`,s.bankAccount&&`A/c No.: ${s.bankAccount}`,s.bankIfsc&&`Branch & IFSC: ${s.bankIfsc}`].filter(Boolean).map(value=>`<div>${escapeHtml(value)}</div>`).join("");
  return `<article class="invoice panel"><header class="panel-title"><div><span class="eyebrow">Tax Invoice</span><h2>${escapeHtml(s.name)}</h2>${sellerDetails}</div><div><strong>Invoice ${escapeHtml(d.invoice_number)}</strong><div>Dated: ${escapeHtml(d.invoice_date)}</div><div>Due: ${escapeHtml(d.due_date)}</div><div>Sale type: ${escapeHtml(d.sale_type)}</div></div></header><section class="invoice-party"><h3>Buyer (Bill to)</h3><strong>${escapeHtml(b.name)}</strong>${buyerDetails}</section>${table(["#","Description","HSN/SAC","Quantity","Rate","Taxable","GST","Amount"],lineRows)}<section class="metric-grid"><article class="metric-card"><span>Taxable value</span><strong>₹${money(invoice.subtotal)}</strong></article><article class="metric-card"><span>CGST</span><strong>₹${money(invoice.cgstTotal)}</strong></article><article class="metric-card"><span>SGST</span><strong>₹${money(invoice.sgstTotal)}</strong></article><article class="metric-card"><span>Grand total</span><strong>₹${money(invoice.grandTotal)}</strong><small>${qty(invoice.totalQuantity)} total quantity</small></article></section><section class="panel"><h3>Amount chargeable (in words)</h3><p><strong>${escapeHtml(invoice.amountWords)}</strong></p></section><h3>Tax breakdown</h3>${table(["HSN/SAC","Taxable","CGST rate","CGST","SGST rate","SGST","Total tax"],taxRows)}<section class="invoice-footer"><div><h3>Tax amount (in words)</h3><p>${escapeHtml(invoice.taxWords)}</p>${s.pan?`<p>Company PAN: <strong>${escapeHtml(s.pan)}</strong></p>`:""}<p>We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.</p></div><div><h3>Company bank details</h3>${bank||"<p>Bank details are not configured for this company.</p>"}<p><strong>for ${escapeHtml(s.name)}</strong><br>Authorised Signatory</p></div></section></article>`;
}

function chunks(value:string,size=28):string[]{const result:string[]=[];for(let index=0;index<value.length;index+=size)result.push(value.slice(index,index+size));return result.length?result:[""];}
export function saleInvoicePdfRows(invoice:SaleInvoiceModel):Row[]{const d=invoice.document,s=invoice.seller,b=invoice.buyer;const rows:Row[]=[{Section:"Invoice",Particulars:"Invoice number",Value:d.invoice_number},{Section:"Invoice",Particulars:"Date / due",Value:`${d.invoice_date} / ${d.due_date??""}`},{Section:"Seller",Particulars:s.name,Value:`GSTIN ${s.gstin||"N/A"}`},...s.address.map(value=>({Section:"Seller",Particulars:"Address",Value:value})),{Section:"Buyer",Particulars:String(b.name??""),Value:`GSTIN ${b.gst_number??"N/A"}`},...((b.address_lines as string[])??[]).map(value=>({Section:"Buyer",Particulars:"Address",Value:value}))];for(const line of invoice.lines as any[])rows.push({Section:"Item",Particulars:`${line.code} ${line.name}`.slice(0,28),Value:`${line.quantity_display} @ ${line.rate_display} = ${money(line.line_total_paise)}`});for(const tax of invoice.taxRows)rows.push({Section:"Tax",Particulars:`HSN ${tax.hsn} CGST ${tax.cgst_rate} SGST ${tax.sgst_rate}`,Value:money(tax.total_tax_paise)});rows.push({Section:"Total",Particulars:"Taxable / GST",Value:`${money(invoice.subtotal)} / ${money(invoice.gstTotal)}`},{Section:"Total",Particulars:"Grand total",Value:money(invoice.grandTotal)},...chunks(invoice.amountWords).map((value,index)=>({Section:"Amount words",Particulars:index?"":"INR",Value:value})));for(const [label,value] of [["Bank",s.bankName],["Account",s.bankAccount],["Branch and IFSC",s.bankIfsc],["PAN",s.pan]] as const)if(value)rows.push({Section:"Bank",Particulars:label,Value:value});return rows;}

function table(headers:string[],rows:unknown[][]):string{return `<section class="panel"><div class="table-wrap"><table><thead><tr>${headers.map(value=>`<th>${escapeHtml(value)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${value??""}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>`;}
