import { Hono } from "hono";
import { describe,expect,it } from "vitest";
import customers from "../../src/routes/customers";
import masters from "../../src/routes/masters";
import { permissionsFor } from "../../src/security/permissions";
import type { AppVariables,AuthUser,Env } from "../../src/types";

const user:AuthUser={id:1,name:"Admin",email:"admin@example.invalid",role:"ADMIN",companyId:1,activeCompanyId:1,forcePasswordChange:false,permissions:permissionsFor("ADMIN"),csrfToken:"csrf",sessionId:1};
type Result={results:Record<string,unknown>[]};
class Statement{params:unknown[]=[];constructor(readonly db:FakeDb,readonly query:string){}bind(...params:unknown[]){this.params=params;return this;}async first(){return this.db.result(this).results[0]??null;}async all(){return this.db.result(this);}}
class FakeDb{statements:Statement[]=[];prepare(query:string){const statement=new Statement(this,query);this.statements.push(statement);return statement;}result(statement:Statement):Result{if(statement.query.startsWith("SELECT id,code,name,contact_person"))return{results:[{id:1,code:"CUS",name:"Customer",mobile:"999",gst_number:"27BUYER"}]};if(statement.query.startsWith("SELECT COALESCE((SELECT SUM"))return{results:[{opening_paise:1000}]};if(statement.query.startsWith("SELECT e.date"))return{results:[{date:"2026-07-01",kind:"SALE",particulars:"To Sales GST",reference:"INV-1",debit_paise:2000,credit_paise:0,id:2},{date:"2026-07-02",kind:"CUSTOMER_RECEIPT",particulars:"By BANK",reference:"RCPT-1",debit_paise:0,credit_paise:500,id:3}]};if(statement.query.includes("FROM sale_lines sl JOIN sales s"))return{results:[{id:5,sale_id:3,company_id:1,challan_number:"INV-3",challan_date:"2026-07-03",item_code:"ITM",item_name:"Tool",quantity_milliunits:1000,unit:"pcs",payment_status:"UNPAID"}]};return{results:[]};}async batch(statements:Statement[]){return statements.map(statement=>this.result(statement));}}
function app(route:"masters"|"customers",db:FakeDb){const hono=new Hono<{Bindings:Env;Variables:AppVariables}>();hono.use("*",async(c,next)=>{c.set("user",user);await next();});hono.route(route==="masters"?"/masters":"/customers",route==="masters"?masters:customers);return{hono,env:{DB:db as unknown as D1Database} as Env};}

describe("customer read parity routes",()=>{
  it("builds a running statement from receivables and payments without adding sales again",async()=>{const db=new FakeDb(),{hono,env}=app("masters",db);const response=await hono.request("http://local/masters/customers/1?date_from=2026-04-01&date_to=2026-07-31",{},env);expect(response.status).toBe(200);const html=await response.text();expect(html).toContain("Opening Balance");expect(html).toContain("30.00 Dr");expect(html).toContain("25.00 Dr");const accountingSql=db.statements.find(statement=>statement.query.startsWith("SELECT e.date"))!.query;expect(accountingSql).toContain("FROM receivables");expect(accountingSql).toContain("FROM payments");expect(accountingSql).not.toContain("FROM sales");});
  it("renders the complete legacy customer profile and does not silently cap statement rows",async()=>{const db=new FakeDb(),{hono,env}=app("masters",db);const response=await hono.request("http://local/masters/customers/1?date_from=2026-04-01&date_to=2026-07-31",{},env);expect(response.status).toBe(200);const html=await response.text();for(const section of ["Overview","Invoices","Challans","Stock","Payments","Notes / Documents","Account Statement"])expect(html).toContain(section);const ledger=db.statements.find(statement=>statement.query.startsWith("SELECT e.date"))!.query;expect(ledger).not.toMatch(/LIMIT\s+2001/i);});
  it("exports the overall customer profile instead of only the ledger",async()=>{const db=new FakeDb(),{hono,env}=app("masters",db);const response=await hono.request("http://local/masters/customers/1/export/csv?date_from=2026-04-01&date_to=2026-07-31",{},env);expect(response.status).toBe(200);expect(response.headers.get("content-disposition")).toContain("customer-1.csv");const csv=await response.text();expect(csv).toContain("Section");expect(csv).toContain("Summary");expect(csv).toContain("Customer");expect(csv).toContain("Pending Stock");});
  it("rejects invalid statement dates before they become a worker exception or D1 query",async()=>{const db=new FakeDb(),{hono,env}=app("masters",db);const response=await hono.request("http://local/masters/customers/1?date_from=2026-02-30",{},env);expect(response.status).toBe(400);expect(await response.text()).toContain("Invalid from date");expect(db.statements).toHaveLength(0);});
  it("returns actual customer sale lines as challans instead of unrelated company transfers",async()=>{const db=new FakeDb(),{hono,env}=app("customers",db);const response=await hono.request("http://local/customers/1/challans?date_from=2026-04-01&date_to=2026-07-31",{},env);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({challans:[{challan_number:"INV-3",item_name:"ITM - Tool (pcs)",status:"Pending",pdf_url:"/transactions/sale/3/export/pdf"}]});const statement=db.statements.at(-1)!;expect(statement.query).toContain("FROM sale_lines sl JOIN sales s");expect(statement.query).not.toContain("inter_company_transfers");expect(statement.params).toEqual([1,1,"2026-04-01","2026-07-31"]);});
});
