import { describe,expect,it } from "vitest";
import { AccountingHandler } from "../../src/accounting";
import { planPurchaseEdit,planSaleEdit } from "../../src/accounting/fifo-edit-cascade";
import type { AccountingEnvelope } from "../../src/accounting/types";

type Row=Record<string,number|string|null>;
class Stmt{params:unknown[]=[];constructor(readonly query:string,readonly db:AuditDb){}bind(...p:unknown[]){this.params=p;return this;}first<T>(){return Promise.resolve(this.db.first(this.query) as T);}all<T>(){return Promise.resolve({results:this.db.all(this.query)} as T);}}
class AuditDb{
 batches:Stmt[][]=[]; replay:Row|null=null; mode:"normal"|"partialFifo"|"saleVoid"|"salePaidAllocation"|"purchaseVoid"|"transferVoid"|"transferSettled"|"paymentCreate"="normal";
 prepare(q:string){return new Stmt(q,this);}batch<T>(s:Stmt[]){this.batches.push(s);if(s.every(x=>x.query.startsWith("SELECT COALESCE(MAX")))return Promise.resolve(s.map(()=>({results:[{id:100}]})) as T);return Promise.resolve(s.map(()=>({success:true,results:[]})) as T);}
 first(q:string):Row|null{if(q.startsWith("SELECT request_digest"))return this.replay;if(q.includes("FROM sales WHERE"))return ["saleVoid","salePaidAllocation"].includes(this.mode)?{id:8,paid_amount_paise:0}:{id:8,paid_amount_paise:0,customer_id:3};if(q.includes("FROM purchases WHERE"))return{id:7,company_id:1,stock_book_id:2,supplier_id:9,paid_amount_paise:0};if(q.includes("FROM inter_company_transfers WHERE"))return{id:6,transfer_date:"2026-01-02"};if(q.includes("JOIN stock_books"))return{book_type:"CASH",allow_gst_purchase:1,allow_cash_purchase:1,allow_gst_sale:1,allow_cash_sale:1};if(q.includes("FROM companies")||q.includes("FROM stock_books")||q.includes("FROM suppliers")||q.includes("FROM customers")||q.includes("FROM payment_modes"))return{id:1};if(q.includes("FROM items"))return{count:1};if(q.includes("settled_amount_paise"))return{count:0};if(q.includes("COUNT(*)"))return{count:this.mode==="salePaidAllocation"?1:0};return null;}
 all(q:string):Row[]{if(q.includes("FROM purchase_lines"))return[{id:21,item_id:4,rate_ten_thousandths:120000,layer_id:31,original_quantity_milliunits:10000,available_quantity_milliunits:4000}];if(q.includes("SELECT id,company_id,stock_book_id,item_id")&&q.includes("transaction_type='PURCHASE'"))return[{id:41,company_id:1,stock_book_id:2,item_id:4}];if(q.includes("FROM fifo_layers WHERE company_id")&&this.mode==="partialFifo")return[{id:31,source_date:"2026-01-01",available_quantity_milliunits:1000,unit_cost_ten_thousandths:100000}];if(q.includes("FROM receivables")&&this.mode==="paymentCreate")return[{id:10,company_id:1,party_id:3,due_date:null,document_date:"2026-01-01",total_amount_paise:10000,paid_amount_paise:0}];if(q.includes("FROM inter_company_ledger_entries")&&this.mode==="transferSettled")return[{id:60,status:"PENDING",settled_amount_paise:1}];if(q.includes("fifo_consumptions")&&((q.includes("source_type='SALE'")&&this.mode==="saleVoid")||(q.includes("source_type='TRANSFER'")&&this.mode==="transferVoid")))return[{fifo_layer_id:31,quantity_milliunits:2000,value_paise:200}];if(q.includes("stock_ledger_entries")&&this.mode==="saleVoid")return[{company_id:1,stock_book_id:2,item_id:4,quantity_out_milliunits:2000,value_paise:200}];if(q.includes("stock_ledger_entries")&&this.mode==="purchaseVoid")return[{company_id:1,stock_book_id:2,item_id:4,quantity_in_milliunits:2000,value_paise:200}];if(q.includes("stock_ledger_entries")&&this.mode==="transferVoid")return[{company_id:1,stock_book_id:2,item_id:4,quantity_in_milliunits:0,quantity_out_milliunits:2000,value_paise:200}];return[];}
 finalSql(){return this.batches.at(-1)?.map(x=>x.query).join("\n")??"";}
}
const env=(type:string,payload:AccountingEnvelope["payload"]):AccountingEnvelope=>({type,userId:1,companyId:1,idempotencyKey:`${type}-key`,requestDigest:`${type}-digest`,payload});
const base={companyId:1,stockBookId:2,referenceNumber:"DOC-1",date:"2026-01-02",lines:[{itemId:4,quantity:"2",rate:"12"}]};

describe("exhaustive accounting FIFO mutation audit",()=>{
 it("purchase create atomically writes document, layer, ledger, balance and payable",async()=>{const db=new AuditDb();await new AccountingHandler(db as unknown as D1Database).execute(env("purchase.create",{...base,supplierId:9,documentType:"CASH"}));const q=db.finalSql();for(const token of ["INSERT INTO purchases","INSERT INTO fifo_layers","INSERT INTO stock_ledger_entries","INSERT INTO inventory_balances","INSERT INTO payables","INSERT INTO audit_logs","SET status='COMMITTED'"])expect(q).toContain(token);});
 it("payment create synchronizes both the outstanding row and its source document",async()=>{const db=new AuditDb();db.mode="paymentCreate";await new AccountingHandler(db as unknown as D1Database).execute(env("payment.create",{companyId:1,paymentType:"CUSTOMER_RECEIPT",partyId:3,date:"2026-01-02",mode:"BANK",amount:"50"}));const q=db.finalSql();expect(q).toContain("UPDATE receivables");expect(q).toContain("UPDATE sales");});
 it("sale create preserves intentional negative stock with full quantity and zero uncovered FIFO cost",async()=>{const db=new AuditDb();await new AccountingHandler(db as unknown as D1Database).execute(env("sale.create",{...base,customerId:3,documentType:"CASH"}));const statements=db.batches.at(-1)!;const ledger=statements.find(x=>x.query.startsWith("INSERT INTO stock_ledger_entries"))!;expect(ledger.params).toContain(2000);expect(ledger.params).toContain(0);const balance=statements.find(x=>x.query.startsWith("INSERT INTO inventory_balances"))!;expect(balance.params).toContain(-2000);expect(balance.params).toContain(0);expect(db.finalSql()).not.toContain("INSERT INTO fifo_consumptions");});
 it("rejects duplicate sale item lines before FIFO planning",async()=>{const db=new AuditDb();await expect(new AccountingHandler(db as unknown as D1Database).execute(env("sale.create",{...base,customerId:3,documentType:"CASH",lines:[...base.lines,...base.lines]}))).rejects.toThrow(/each item only once/);expect(db.batches).toHaveLength(0);});
 it("rejects duplicate transfer item lines before FIFO planning",async()=>{const db=new AuditDb();await expect(new AccountingHandler(db as unknown as D1Database).execute(env("transfer.create",{...base,toCompanyId:2,toStockBookId:3,lines:[...base.lines,...base.lines]}))).rejects.toThrow(/each item only once/);expect(db.batches).toHaveLength(0);});
 it("sale and transfer split partial FIFO coverage from zero-cost uncovered quantity",async()=>{const saleDb=new AuditDb();saleDb.mode="partialFifo";await new AccountingHandler(saleDb as unknown as D1Database).execute(env("sale.create",{...base,customerId:3,documentType:"CASH"}));const saleBatch=saleDb.batches.at(-1)!;expect(saleBatch.find(x=>x.query.startsWith("INSERT INTO stock_ledger_entries"))!.params).toEqual(expect.arrayContaining([2000,1000]));expect(saleBatch.find(x=>x.query.startsWith("INSERT INTO inventory_balances"))!.params).toEqual(expect.arrayContaining([-2000,-1000]));expect(saleBatch.find(x=>x.query.startsWith("INSERT INTO fifo_consumptions"))!.params).toEqual(expect.arrayContaining([1000,1000]));const transferDb=new AuditDb();transferDb.mode="partialFifo";await new AccountingHandler(transferDb as unknown as D1Database).execute(env("transfer.create",{...base,toCompanyId:2,toStockBookId:3}));const ledgers=transferDb.batches.at(-1)!.filter(x=>x.query.startsWith("INSERT INTO stock_ledger_entries"));expect(ledgers).toHaveLength(2);expect(ledgers[0]!.params).toEqual(expect.arrayContaining([1000,1000]));expect(ledgers[1]!.params).toEqual(expect.arrayContaining([1000,0]));});
 it("transfer create preserves intentional negative stock as a zero-value OUT movement",async()=>{const db=new AuditDb();await new AccountingHandler(db as unknown as D1Database).execute(env("transfer.create",{...base,toCompanyId:2,toStockBookId:3}));const statements=db.batches.at(-1)!;const ledger=statements.find(x=>x.query.startsWith("INSERT INTO stock_ledger_entries"))!;expect(ledger.params).toContain(2000);expect(ledger.params).toContain(0);const balance=statements.find(x=>x.query.startsWith("INSERT INTO inventory_balances"))!;expect(balance.params).toContain(-2000);expect(balance.params).toContain(0);});
 it("sale edit preserves a FIFO shortage and rebuilds the full negative inventory movement",async()=>{const db=new AuditDb();const p=await planSaleEdit(db as unknown as D1Database,{id:8,...base,customerId:3,documentType:"CASH"},1),statements=p.mutations;expect(statements.some(x=>x.sql.startsWith("INSERT INTO fifo_consumptions"))).toBe(false);const ledger=statements.find(x=>x.sql.startsWith("INSERT INTO stock_ledger_entries"))!;expect(ledger.params).toContain(2000);expect(ledger.params).toContain(0);const balance=statements.find(x=>x.sql.startsWith("INSERT INTO inventory_balances")&&x.params.includes(-2000))!;expect(balance.params).toContain(0);});
 it("purchase edit rejects consumed quantity shrink and never emits a write batch",async()=>{const db=new AuditDb();await expect(planPurchaseEdit(db as unknown as D1Database,{id:7,...base,supplierId:9,documentType:"CASH",lines:[{itemId:4,quantity:"5",rate:"12"}]},1)).rejects.toThrow(/below the quantity already consumed/);expect(db.batches).toHaveLength(0);});
 it("purchase edit cascade covers consumptions, sale profit, transfer ledger, exact inventory and payable invariants",async()=>{const db=new AuditDb(),p=await planPurchaseEdit(db as unknown as D1Database,{id:7,...base,supplierId:9,documentType:"CASH",lines:[{itemId:4,quantity:"10",rate:"15"}]},1),q=p.mutations.map(x=>x.sql).join("\n");for(const token of ["UPDATE fifo_consumptions","UPDATE sale_lines SET","UPDATE sales SET","UPDATE transfer_lines SET","UPDATE inter_company_ledger_entries SET","balance_amount_paise","UPDATE payables SET","quantity_milliunits=excluded.quantity_milliunits"])expect(q).toContain(token);});
 it("sale void restores FIFO and inventory before deleting dependent rows in the atomic batch",async()=>{const db=new AuditDb();db.mode="saleVoid";await new AccountingHandler(db as unknown as D1Database).execute(env("sale.void",{id:8,companyId:1}));const q=db.finalSql();expect(q.indexOf("UPDATE fifo_layers")).toBeLessThan(q.indexOf("DELETE FROM fifo_consumptions"));expect(q).toContain("INSERT INTO inventory_balances");expect(q).toContain("DELETE FROM receivables");});
 it("sale void refuses any live payment allocation even if legacy source totals are stale",async()=>{const db=new AuditDb();db.mode="salePaidAllocation";await expect(new AccountingHandler(db as unknown as D1Database).execute(env("sale.void",{id:8,companyId:1}))).rejects.toThrow(/receipt allocation/);expect(db.batches).toHaveLength(0);});
 it("purchase void reverses inventory and deletes only an unconsumed layer cascade",async()=>{const db=new AuditDb();db.mode="purchaseVoid";await new AccountingHandler(db as unknown as D1Database).execute(env("purchase.void",{id:7,companyId:1}));const q=db.finalSql();expect(q).toContain("INSERT INTO inventory_balances");expect(q).toContain("DELETE FROM payables");expect(q).toContain("DELETE FROM fifo_layers");});
 it("transfer void restores FIFO, reverses ledger balances, and clears transfer dependencies",async()=>{const db=new AuditDb();db.mode="transferVoid";await new AccountingHandler(db as unknown as D1Database).execute(env("transfer.void",{id:6,companyId:1}));const q=db.finalSql();for(const token of ["INSERT INTO inventory_balances","DELETE FROM fifo_consumptions","DELETE FROM stock_ledger_entries","DELETE FROM inter_company_ledger_entries"])expect(q).toContain(token);});
 it("transfer void rejects settled inter-company entries before any mutation batch",async()=>{const db=new AuditDb();db.mode="transferSettled";await expect(new AccountingHandler(db as unknown as D1Database).execute(env("transfer.void",{id:6,companyId:1}))).rejects.toThrow(/has been settled/);expect(db.batches).toHaveLength(0);});
 it("committed retries replay with no writes, digest collisions reject, and in-progress retries reject",async()=>{const db=new AuditDb(),cmd=env("purchase.create",{...base,supplierId:9,documentType:"CASH"});db.replay={request_digest:"purchase.create-digest",status:"COMMITTED",result_type:"Purchase",result_id:7};await expect(new AccountingHandler(db as unknown as D1Database).execute(cmd)).resolves.toMatchObject({id:7,replayed:true});expect(db.batches).toHaveLength(0);db.replay={...db.replay,request_digest:"different"};await expect(new AccountingHandler(db as unknown as D1Database).execute(cmd)).rejects.toThrow(/different request/);db.replay={...db.replay,request_digest:"purchase.create-digest",status:"PENDING"};await expect(new AccountingHandler(db as unknown as D1Database).execute(cmd)).rejects.toThrow(/already in progress/);});
});
