import { describe,expect,it } from "vitest";
import { planPurchaseEdit,planSaleEdit } from "../../src/accounting/fifo-edit-cascade";

class Statement{constructor(readonly q:string,readonly db:FakeDb){} bind(...p:unknown[]){this.db.params.push([this.q,p]);return this;} first<T>(){return Promise.resolve(this.db.first(this.q) as T);} all<T>(){return Promise.resolve({results:this.db.all(this.q)} as T);}}
class FakeDb{params:[string,unknown[]][]=[];constructor(readonly mode:"purchase"|"sale"="purchase"){} prepare(q:string){return new Statement(q,this);} batch<T>(s:Statement[]){return Promise.resolve(s.map(()=>({results:[{id:100}]})) as T);} first(q:string){if(q.includes("FROM purchases"))return{id:7,paid_amount_paise:0,is_void:0};if(q.includes("FROM sales"))return{id:8,paid_amount_paise:0,customer_id:3,is_void:0};return null;} all(q:string){if(q.includes("FROM purchase_lines"))return[{id:21,item_id:4,layer_id:31,original_quantity_milliunits:10000,available_quantity_milliunits:4000}];if(q.includes("FROM fifo_consumptions")&&q.includes("source_type='SALE'"))return[{fifo_layer_id:31,quantity_milliunits:2000,value_paise:200}];if(q.includes("FROM fifo_layers")&&this.mode==="sale")return[{id:31,source_date:"2026-01-01",available_quantity_milliunits:4000,unit_cost_ten_thousandths:100000}];return[];}}
const purchase={id:7,companyId:1,stockBookId:2,supplierId:9,documentType:"CASH" as const,referenceNumber:"P-7",date:"2026-01-02",lines:[{itemId:4,quantity:"10",rate:"12"}]};
describe("FIFO edit cascade",()=>{
 it("retargets consumed purchase cost and all derived sale/transfer values",async()=>{const p=await planPurchaseEdit(new FakeDb() as unknown as D1Database,purchase,1),sql=p.mutations.map(x=>x.sql).join("\n");expect(sql).toContain("UPDATE fifo_consumptions SET rate_ten_thousandths");expect(sql).toContain("UPDATE sale_lines SET fifo_cost_paise");expect(sql).toContain("UPDATE sales SET fifo_cost_paise");expect(sql).toContain("transaction_type IN('SALE','TRANSFER')");expect(sql).toContain("UPDATE payables");});
 it("rejects shrinking below already consumed stock before any write",async()=>{await expect(planPurchaseEdit(new FakeDb() as unknown as D1Database,{...purchase,lines:[{itemId:4,quantity:"5",rate:"12"}]},1)).rejects.toThrow(/below the quantity already consumed/);});
 it("restores and reconsumes sale FIFO in one mutation plan",async()=>{const p=await planSaleEdit(new FakeDb("sale") as unknown as D1Database,{id:8,companyId:1,stockBookId:2,customerId:3,documentType:"CASH",referenceNumber:"S-8",date:"2026-01-03",lines:[{itemId:4,quantity:"2",rate:"20"}]},1),sql=p.mutations.map(x=>x.sql).join("\n");expect(sql).toContain("DELETE FROM fifo_consumptions");expect(sql).toContain("INSERT INTO fifo_consumptions");expect(sql).toContain("UPDATE receivables");expect(sql).toContain("gross_profit_paise");});
});
