import { describe,expect,it } from "vitest";
import { planPurchaseEdit,planSaleEdit } from "../../src/accounting/fifo-edit-cascade";

class Statement{constructor(readonly q:string,readonly db:FakeDb){} bind(...p:unknown[]){this.db.params.push([this.q,p]);return this;} first<T>(){return Promise.resolve(this.db.first(this.q) as T);} all<T>(){return Promise.resolve({results:this.db.all(this.q)} as T);}}
class FakeDb{params:[string,unknown[]][]=[];constructor(readonly mode:"purchase"|"sale"|"saleFullyConsumed"|"purchaseReturned"="purchase"){} prepare(q:string){return new Statement(q,this);} batch<T>(s:Statement[]){return Promise.resolve(s.map(()=>({results:[{id:100}]})) as T);} first(q:string){if(q.includes("FROM purchases"))return{id:7,company_id:1,stock_book_id:2,supplier_id:9,paid_amount_paise:0,is_void:0};if(q.includes("FROM sales"))return{id:8,paid_amount_paise:0,customer_id:3,is_void:0};if(q.includes("JOIN stock_books"))return{book_type:"CASH",allow_gst_purchase:1,allow_cash_purchase:1,allow_gst_sale:1,allow_cash_sale:1};if(q.includes("FROM companies")||q.includes("FROM stock_books")||q.includes("FROM suppliers")||q.includes("FROM customers"))return{id:1};if(q.includes("FROM items"))return{count:1};if(q.includes("settled_amount_paise"))return{count:0};if(q.includes("FROM inter_company_ledger_entries issued"))return{count:this.mode==="purchaseReturned"?1:0};return null;} all(q:string){if(q.includes("FROM purchase_lines"))return[{id:21,item_id:4,rate_ten_thousandths:120000,layer_id:31,original_quantity_milliunits:10000,available_quantity_milliunits:4000}];if(q.includes("transaction_type='PURCHASE'"))return[{id:41,company_id:1,stock_book_id:2,item_id:4}];if(q.includes("FROM fifo_consumptions")&&q.includes("source_type='SALE'")&&!q.includes("FROM fifo_layers"))return[{fifo_layer_id:31,quantity_milliunits:2000,value_paise:2000}];if(q.includes("stock_ledger_entries")&&(this.mode==="sale"||this.mode==="saleFullyConsumed"))return[{company_id:1,stock_book_id:2,item_id:4,quantity_out_milliunits:2000,value_paise:2000}];if(q.includes("FROM fifo_layers")&&this.mode==="sale")return[{id:31,source_date:"2026-01-01",available_quantity_milliunits:4000,unit_cost_ten_thousandths:100000}];if(q.includes("FROM fifo_layers")&&this.mode==="saleFullyConsumed"&&q.includes("id IN"))return[{id:31,source_date:"2026-01-01",available_quantity_milliunits:0,unit_cost_ten_thousandths:100000}];return[];}}
const purchase={id:7,companyId:1,stockBookId:2,supplierId:9,documentType:"CASH" as const,referenceNumber:"P-7",date:"2026-01-02",lines:[{itemId:4,quantity:"10",rate:"12"}]};
describe("FIFO edit cascade",()=>{
 it("retargets consumed purchase cost and all derived sale/transfer values",async()=>{const p=await planPurchaseEdit(new FakeDb() as unknown as D1Database,purchase,1),sql=p.mutations.map(x=>x.sql).join("\n");expect(sql).toContain("UPDATE fifo_consumptions SET rate_ten_thousandths");expect(sql).toContain("UPDATE sale_lines SET");expect(sql).toContain("UPDATE sales SET");expect(sql).toContain("UPDATE transfer_lines SET");expect(sql).toContain("UPDATE inter_company_ledger_entries SET");expect(sql).toContain("UPDATE payables SET");expect(sql).toContain("ON CONFLICT(company_id,stock_book_id,item_id) DO UPDATE SET quantity_milliunits=excluded.quantity_milliunits");});
 it("rejects shrinking below already consumed stock before any write",async()=>{await expect(planPurchaseEdit(new FakeDb() as unknown as D1Database,{...purchase,lines:[{itemId:4,quantity:"5",rate:"12"}]},1)).rejects.toThrow(/below the quantity already consumed/);});
 it("restores and reconsumes sale FIFO and its inventory balance in one mutation plan",async()=>{const p=await planSaleEdit(new FakeDb("sale") as unknown as D1Database,{id:8,companyId:1,stockBookId:2,customerId:3,documentType:"CASH",referenceNumber:"S-8",date:"2026-01-03",lines:[{itemId:4,quantity:"2",rate:"20"}]},1),sql=p.mutations.map(x=>x.sql).join("\n"),balances=p.mutations.filter(x=>x.sql.startsWith("INSERT INTO inventory_balances"));expect(sql).toContain("DELETE FROM fifo_consumptions");expect(sql).toContain("INSERT INTO fifo_consumptions");expect(sql).toContain("UPDATE receivables");expect(sql).toContain("gross_profit_paise");expect(balances).toHaveLength(2);expect(balances[0]!.params).toEqual(expect.arrayContaining([2000,2000]));expect(balances[1]!.params).toEqual(expect.arrayContaining([-2000,-2000]));});
 it("allows a sale edit to exceed all available FIFO while keeping full quantity in ledger and balance",async()=>{const p=await planSaleEdit(new FakeDb() as unknown as D1Database,{id:8,companyId:1,stockBookId:2,customerId:3,documentType:"CASH",referenceNumber:"S-NEG",date:"2026-01-03",lines:[{itemId:4,quantity:"2",rate:"20"}]},1);expect(p.mutations.some(x=>x.sql.startsWith("INSERT INTO fifo_consumptions"))).toBe(false);const ledger=p.mutations.find(x=>x.sql.startsWith("INSERT INTO stock_ledger_entries"))!;expect(ledger.params).toContain(2000);expect(ledger.params).toContain(0);const balance=p.mutations.find(x=>x.sql.startsWith("INSERT INTO inventory_balances")&&x.params.includes(-2000))!;expect(balance.params).toContain(0);});
 it("includes a fully consumed prior layer when restoring and reallocating a sale",async()=>{const p=await planSaleEdit(new FakeDb("saleFullyConsumed") as unknown as D1Database,{id:8,companyId:1,stockBookId:2,customerId:3,documentType:"CASH",referenceNumber:"S-FULL",date:"2026-01-03",lines:[{itemId:4,quantity:"2",rate:"20"}]},1);expect(p.mutations.some(x=>x.sql.startsWith("INSERT INTO fifo_consumptions"))).toBe(true);expect(p.mutations.find(x=>x.sql.startsWith("UPDATE fifo_layers SET available_quantity_milliunits=available_quantity_milliunits+"))!.sql).toContain("+5000000");});
 it("rejects duplicate sale edit items before any FIFO reads",async()=>{const db=new FakeDb("sale");await expect(planSaleEdit(db as unknown as D1Database,{id:8,companyId:1,stockBookId:2,customerId:3,documentType:"CASH",referenceNumber:"S-DUP",date:"2026-01-03",lines:[{itemId:4,quantity:"1",rate:"20"},{itemId:4,quantity:"1",rate:"20"}]},1)).rejects.toThrow(/each item only once/);expect(db.params.map(([query])=>query)).toEqual([expect.stringContaining("FROM sales")]);});
 it("accepts zero-rate purchase and sale edits like create",async()=>{await expect(planPurchaseEdit(new FakeDb() as unknown as D1Database,{...purchase,lines:[{itemId:4,quantity:"10",rate:"0"}]},1)).resolves.toBeDefined();await expect(planSaleEdit(new FakeDb("sale") as unknown as D1Database,{id:8,companyId:1,stockBookId:2,customerId:3,documentType:"CASH",referenceNumber:"S-ZERO",date:"2026-01-03",lines:[{itemId:4,quantity:"2",rate:"0"}]},1)).resolves.toBeDefined();});
 it("blocks purchase repricing after its stock enters an inter-company return chain",async()=>{await expect(planPurchaseEdit(new FakeDb("purchaseReturned") as unknown as D1Database,{...purchase,lines:[{itemId:4,quantity:"10",rate:"15"}]},1)).rejects.toThrow(/return chain/);});
});
