import type { AuthUser } from "../types";
import { can } from "../security/permissions";
import { assetPaths } from "../generated/assets";

export function escapeHtml(value: unknown): string {
  return String(value ?? "").replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  })[character] ?? character);
}
export function money(paise: unknown): string {
  const value = Number(paise ?? 0) / 100;
  return value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function qty(milli: unknown): string {
  return (Number(milli ?? 0) / 1000).toLocaleString("en-IN", { maximumFractionDigits: 3 });
}

function nav(user: AuthUser, title: string): string {
  const links: Array<[string, string, string, string]> = [
    ["dashboard", "/dashboard", "Dashboard", "layout-dashboard"], ["items", "/masters/items", "Items", "gem"],
    ["customers", "/masters/customers", "Customers", "users"], ["suppliers", "/masters/suppliers", "Suppliers", "truck"],
    ["purchase", "/transactions/purchase", "Purchase", "shopping-bag"], ["sale", "/transactions/sale", "Sale", "receipt-text"],
    ["transfer", "/transactions/transfer", "Transfer", "arrow-left-right"], ["opening", "/transactions/opening", "Opening", "folder-open"],
    ["payments", "/finance/payments", "Payments", "credit-card"], ["outstanding", "/finance/outstanding", "Outstanding", "wallet-cards"],
    ["stock", "/reports/current-stock", "Stock", "boxes"], ["inter_company", "/reports/inter-company", "Inter Co", "building-2"],
    ["reports", "/reports", "Reports", "chart-no-axes-combined"], ["users", "/users", "Users", "user-cog"],
  ];
  return links.filter(([module]) => can(user, module)).map(([, href, label, icon]) => `<a data-nav-icon="${icon}" href="${href}" class="${label.toLowerCase() === title.toLowerCase() ? "active" : ""}">${escapeHtml(label)}</a>`).join("");
}

function documentHead(title: string): string {
  return `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)} · FAstockFlow</title><script>(()=>{const theme=localStorage.getItem("fastockflow-theme");if(theme==="dark")document.documentElement.dataset.theme="dark";})();</script><link rel="icon" href="${assetPaths.icon}"><link rel="stylesheet" href="${assetPaths.css}"></head>`;
}

function floatingTools():string {
  return `<div class="floating-tools" data-floating-tools><div class="floating-tool-actions"><button type="button" class="floating-tool-button icon-only" data-tool-toggle="calculator" aria-controls="floating_calculator" aria-expanded="false" aria-label="Calculator" title="Calculator"><span data-icon="calculator"></span></button><button type="button" class="floating-tool-button icon-only" data-tool-toggle="calendar" aria-controls="floating_calendar" aria-expanded="false" aria-label="Calendar" title="Calendar"><span data-icon="calendar-days"></span></button><button type="button" class="floating-tool-button icon-only" data-tool-toggle="music" aria-controls="floating_music" aria-expanded="false" aria-label="Focus mode" title="Focus mode"><span data-icon="headphones"></span></button></div>
  <section id="floating_calculator" class="floating-tool-panel calculator-panel" data-tool-panel="calculator" hidden><div class="tool-panel-title"><strong>Calculator</strong><button type="button" class="tool-close" data-tool-close aria-label="Close calculator">x</button></div><output class="calculator-display" data-calc-display>0</output><div class="calculator-grid">${[["clear","C"],["back","Back"],["%","%"],["/","/"],["7","7"],["8","8"],["9","9"],["*","x"],["4","4"],["5","5"],["6","6"],["-","-"],["1","1"],["2","2"],["3","3"],["+","+"],["negate","+/-"],["0","0"],[".","."],["equals","="]].map(([key,label])=>`<button type="button" data-calc-key="${key}">${label}</button>`).join("")}</div></section>
  <section id="floating_calendar" class="floating-tool-panel calendar-panel" data-tool-panel="calendar" data-calendar-url="/dashboard/calendar-events" hidden><div class="tool-panel-title"><strong>Calendar</strong><button type="button" class="tool-close" data-tool-close aria-label="Close calendar">x</button></div><div class="calendar-toolbar"><button type="button" data-calendar-prev aria-label="Previous month">&lt;</button><strong data-calendar-title></strong><button type="button" data-calendar-next aria-label="Next month">&gt;</button><button type="button" data-calendar-today>Today</button></div><div class="calendar-weekdays" aria-hidden="true"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendar-grid" data-calendar-grid></div><div class="calendar-event-list"><strong data-calendar-selected>Events</strong><div data-calendar-events class="calendar-events"></div></div></section>
  <section id="floating_music" class="floating-tool-panel music-panel" data-tool-panel="music" hidden><div class="tool-panel-title"><div><strong>Focus Mode</strong><small>Manual ambient sound</small></div><button type="button" class="tool-close" data-tool-close aria-label="Close focus mode">x</button></div><div class="music-now"><span class="music-pulse" aria-hidden="true"></span><div><strong data-music-track-name>Rain</strong><small data-music-status>Ready when you are</small></div></div><label>Track<select data-music-track aria-label="Focus mode track"><option value="rain">Rain</option><option value="ocean">Ocean Waves</option><option value="piano">Soft Piano</option><option value="forest">Forest</option><option value="coffee">Coffee Shop</option><option value="lofi">Lo-fi Instrumental</option></select></label><div class="music-controls"><button type="button" data-music-prev aria-label="Previous track"><span data-icon="skip-back"></span></button><button type="button" class="music-play" data-music-toggle aria-label="Play focus mode"><span data-icon="play"></span></button><button type="button" data-music-next aria-label="Next track"><span data-icon="skip-forward"></span></button><button type="button" data-music-mute aria-label="Mute focus mode"><span data-icon="volume-2"></span></button><button type="button" data-music-loop aria-label="Loop focus mode"><span data-icon="repeat"></span></button></div><label>Volume<input type="range" min="0" max="100" value="45" data-music-volume aria-label="Focus mode volume"></label></section></div>`;
}

export function layout(title: string, body: string, user: AuthUser | null, options: { message?: string; scripts?: string; subtitle?: string; company?: { name: string; code?: string } | null; dueAlertCount?: number } = {}): string {
  const message = options.message ? `<div class="flash info">${escapeHtml(options.message)}</div>` : "";
  if (!user) return `<!doctype html><html lang="en">${documentHead(title)}<body><main class="main public-main"><header class="topbar"><div class="topbar-copy"><div class="topbar-title-row"><h1>${escapeHtml(title)}</h1></div><p>Secure stock, billing, payments and company control</p></div></header><div class="content-container">${message}<section class="panel narrow">${body}</section></div></main><script src="${assetPaths.js}"></script>${options.scripts ?? ""}</body></html>`;
  const companyName = options.company?.name ?? (user.activeCompanyId ? "Company workspace" : "All companies");
  const companyCode = options.company?.code?.toUpperCase() ?? "";
  const companyLogo = companyCode === "AI" ? assetPaths.adityaLogo : companyCode === "FML" ? assetPaths.firsttechLogo : assetPaths.icon;
  const appName = companyCode === "AI" ? "Aditya International" : companyCode === "FML" ? "FirstTech Machine LLP" : "FAstockFlow Owner";
  const tagline = companyCode === "AI" ? "Jewellery factory supplies stock control" : companyCode === "FML" ? "Next generation technology stock control" : "Combined FirstTech and Aditya control";
  const bodyClass = companyCode === "AI" ? "theme-aditya" : companyCode === "FML" ? "theme-firsttech" : "theme-default";
  const quickActions = `<div class="quick-actions" aria-label="Quick actions">${can(user,"sale","create")?'<a class="quick-action primary" href="/transactions/sale">Sale</a>':""}${can(user,"purchase","create")?'<a class="quick-action" href="/transactions/purchase">Purchase</a>':""}${can(user,"payments","create")?'<a class="quick-action" href="/finance/payments">Payment</a>':""}</div>`;
  const companyChip = `<a class="company-chip" href="/company/choose" title="${user.companyId ? "Company workspace" : "Change company"}"><img src="${companyLogo}" alt=""><span>${escapeHtml(companyName)}</span></a>`;
  const bell = options.dueAlertCount == null ? "" : `<a class="bell-button" href="/reports/due-alerts" title="Due alerts" aria-label="Due alerts"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"></path><path d="M13.7 21a2 2 0 0 1-3.4 0"></path></svg>${options.dueAlertCount>0?`<span class="alert-badge">${options.dueAlertCount}</span>`:""}</a>`;
  return `<!doctype html><html lang="en">${documentHead(title)}<body class="${bodyClass}"><div class="app-shell"><aside class="sidebar" aria-label="Primary navigation"><button class="sidebar-collapse-button" type="button" data-sidebar-toggle aria-label="Minimize sidebar" title="Minimize sidebar"><span data-icon="panel-left"></span></button><button class="sidebar-hide-button" type="button" data-sidebar-hide aria-label="Hide sidebar" title="Hide sidebar"><span data-icon="chevrons-left"></span></button><a class="brand" href="/dashboard"><span class="brand-mark logo-mark company-brand-mark"><img src="${companyLogo}" alt="${escapeHtml(appName)}"></span><span><strong>${escapeHtml(appName)}</strong><small>${escapeHtml(tagline)}</small></span></a><nav class="nav">${nav(user,title)}</nav><div class="sidebar-footer">${user.companyId?"":`<form method="post" action="/company/all" class="footer-company-form"><input type="hidden" name="csrf_token" value="${escapeHtml(user.csrfToken)}"><input type="hidden" name="next" value="/dashboard"><button class="footer-link ${user.activeCompanyId?"":"active"}" type="submit">All companies</button></form>`}<form action="/logout" method="post"><input type="hidden" name="csrf_token" value="${escapeHtml(user.csrfToken)}"><button class="ghost-button full" type="submit">Logout</button></form></div></aside><button class="sidebar-peek-button" type="button" data-sidebar-show aria-label="Show sidebar" title="Show sidebar"><span data-icon="panel-right"></span></button><main class="main" id="main-content"><header class="topbar"><div class="topbar-copy"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/dashboard">Home</a><span aria-hidden="true">/</span><span aria-current="page">${escapeHtml(title)}</span></nav><div class="topbar-title-row"><button class="back-button" type="button" data-back-button data-back-fallback="/dashboard" aria-label="Go back" title="Back (Esc)"><span data-icon="arrow-left"></span><span>Back</span></button><h1>${escapeHtml(title)}</h1></div><p>${escapeHtml(options.subtitle ?? "Real-time stock, FIFO, payments and inter-company control")}</p></div><div class="topbar-actions"><label class="global-search" aria-label="Search current page"><span data-icon="search"></span><input type="search" placeholder="Search this page" data-global-search autocomplete="off" title="Search this page (Ctrl+F)"></label>${quickActions}${companyChip}${bell}<button class="theme-toggle" type="button" data-theme-toggle aria-label="Toggle dark mode" title="Toggle dark mode"><span data-icon="moon"></span></button><button class="theme-toggle" type="button" data-shortcut-help aria-label="Keyboard shortcuts" title="Keyboard shortcuts (F1)"><span data-icon="keyboard"></span></button><div class="user-chip">${escapeHtml(user.name)} · ${escapeHtml(user.role)}</div></div></header><div class="content-container">${message}${body}</div></main></div>${floatingTools()}<script src="${assetPaths.js}"></script>${options.scripts ?? ""}</body></html>`;
}

export function authLayout(title: string, panel: string, message = ""): string {
  return `<!doctype html><html lang="en">${documentHead(title)}<body class="auth-body"><main class="login-page auth-page"><section class="auth-shell"><aside class="auth-hero"><div class="auth-product-mark"><img src="${assetPaths.icon}" alt="FAstockFlow"><span>FAstockFlow</span></div><div class="auth-hero-copy"><span class="auth-kicker">Jewellery Factory ERP</span><h1>Secure stock, billing, payment, and company control.</h1><p>Choose your company workspace and continue with the login ID assigned to that company.</p></div><div class="auth-trust-grid"><span><strong>FIFO</strong>stock ledgers</span><span><strong>GST/Cash</strong>workflows</span><span><strong>Audit</strong>entry tracking</span></div></aside><section class="auth-panel">${message ? `<div class="flash info">${escapeHtml(message)}</div>` : ""}${panel}</section></section></main><script src="${assetPaths.js}"></script></body></html>`;
}

export function table(headers: string[], rows: unknown[][]): string {
  return `<section class="panel"><div class="table-wrap"><table><thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${cell == null ? "" : String(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>`;
}

export function formField(name: string, label: string, value: unknown = "", type = "text", required = false): string {
  return `<label class="form-field">${escapeHtml(label)}<input type="${escapeHtml(type)}" name="${escapeHtml(name)}" value="${escapeHtml(value)}" ${required ? "required" : ""}></label>`;
}
