import { allocateFifo, gstRate, lineTotals, paymentStatus, quantity, rate, type Money } from "../domain";
import type { PurchaseCommand, SaleCommand } from "./types";
import { dbInt, nextIds, sql, type SqlMutation } from "./sql";
type Row=Record<string,number|string|null>; export type EditPlan={type:"Purchase"|"Sale";id:number;before:Row;mutations:SqlMutation[]};
const ts=()=>new Date().toISOString(), value=(q:bigint,r:bigint)=>(q*r*100n+5_000_000n)/10_000_000n;
const balance=(company:number,book:number,item:number,q:bigint,v:bigint,t:string)=>sql("INSERT INTO inventory_balances(company_id,stock_book_id,item_id,quantity_milliunits,ledger_value_paise,version,updated_at) VALUES(?,?,?,?,?,1,?) ON CONFLICT(company_id,stock_book_id,item_id) DO UPDATE SET quantity_milliunits=quantity_milliunits+excluded.quantity_milliunits,ledger_value_paise=ledger_value_paise+excluded.ledger_value_paise,version=version+1,updated_at=excluded.updated_at",company,book,item,dbInt(q),dbInt(v),t);
const pstatus=(paid:bigint,total:bigint)=>paymentStatus(total as Money,paid as Money);
async function rows(db:D1Database,q:string,...p:unknown[]){return (await db.prepare(q).bind(...p).all<Row>()).results;}
function parse(lines:PurchaseCommand["lines"],taxable:boolean){if(!lines.length)throw new Error("At least one item line is required.");return lines.map(x=>{const q=quantity(x.quantity),r=rate(x.rate),g=gstRate(x.gstPercent??0);if(q<=0n)throw new Error("Quantity must be greater than zero.");if(r<=0n)throw new Error("Rate must be greater than zero.");return{...x,q,r,g,t:lineTotals(q,r,g,taxable)}});}

/** Pure planning phase: all reads and validation precede the caller's one atomic D1 batch. */
export async function planSaleEdit(db:D1Database,data:SaleCommand,userId:number):Promise<EditPlan>{
 if(!data.id)throw new Error("Document ID is required.");const old=await db.prepare("SELECT * FROM sales WHERE id=? AND is_void=0").bind(data.id).first<Row>();if(!old)throw new Error("Sale was not found or is void.");const paid=BigInt(old.paid_amount_paise??0);if(paid>0n&&Number(old.customer_id)!==data.customerId)throw new Error("Customer cannot be changed after receipt allocation.");
 const input=parse(data.lines,data.documentType==="GST"),t=ts(),prior=await rows(db,"SELECT fifo_layer_id,quantity_milliunits,value_paise FROM fifo_consumptions WHERE source_type='SALE' AND source_id=? ORDER BY id",data.id),oldLedger=await rows(db,"SELECT company_id,stock_book_id,item_id,quantity_out_milliunits,value_paise FROM stock_ledger_entries WHERE transaction_type='SALE' AND transaction_id=?",data.id),restored=new Map<number,bigint>();for(const c of prior)restored.set(Number(c.fifo_layer_id),(restored.get(Number(c.fifo_layer_id))??0n)+BigInt(c.quantity_milliunits!));
 const ids=await nextIds(db,["sale_lines","fifo_consumptions","stock_ledger_entries"]),m:SqlMutation[]=[sql("DELETE FROM fifo_consumptions WHERE source_type='SALE' AND source_id=?",data.id),sql("DELETE FROM stock_ledger_entries WHERE transaction_type='SALE' AND transaction_id=?",data.id),sql("DELETE FROM sale_lines WHERE sale_id=?",data.id)];let sub=0n,gst=0n,total=0n,cost=0n,ci=0;
 for(const [id,q] of restored)m.push(sql("UPDATE fifo_layers SET available_quantity_milliunits=available_quantity_milliunits+?,available_value_paise=(available_quantity_milliunits+?)*unit_cost_ten_thousandths*100/10000000,status=CASE WHEN available_quantity_milliunits+?=original_quantity_milliunits THEN 'OPEN' ELSE 'PARTIAL' END,updated_at=? WHERE id=?",dbInt(q),dbInt(q),dbInt(q),t,id));
 for(const row of oldLedger)m.push(balance(Number(row.company_id),Number(row.stock_book_id),Number(row.item_id),BigInt(row.quantity_out_milliunits!),BigInt(row.value_paise!),t));
 for(let i=0;i<input.length;i++){const l=input[i]!,rr=await rows(db,"SELECT id,source_date,available_quantity_milliunits,unit_cost_ten_thousandths FROM fifo_layers WHERE company_id=? AND stock_book_id=? AND item_id=? AND available_quantity_milliunits>0 ORDER BY source_date,id",data.companyId,data.stockBookId,l.itemId),layers=rr.map(x=>({id:Number(x.id),sourceDate:String(x.source_date),availableQuantity:(BigInt(x.available_quantity_milliunits!)+(restored.get(Number(x.id))??0n)) as any,unitCost:BigInt(x.unit_cost_ten_thousandths!) as any})),a=allocateFifo(l.q,layers);const lid=ids.sale_lines+i;sub+=l.t.subtotal;gst+=l.t.gst;total+=l.t.total;cost+=a.coveredCost;m.push(sql("INSERT INTO sale_lines(id,sale_id,item_id,quantity_milliunits,sale_rate_ten_thousandths,gst_basis_points,subtotal_paise,gst_amount_paise,line_total_paise,fifo_cost_paise,gross_profit_paise) VALUES(?,?,?,?,?,?,?,?,?,?,?)",lid,data.id,l.itemId,dbInt(l.q),dbInt(l.r),dbInt(l.g),dbInt(l.t.subtotal),dbInt(l.t.gst),dbInt(l.t.total),dbInt(a.coveredCost),dbInt(l.t.subtotal-a.coveredCost)));for(const c of a.consumptions){if(c.layerId===null)continue;const z=a.layers.find(x=>x.id===c.layerId)!;m.push(sql("UPDATE fifo_layers SET available_quantity_milliunits=?,available_value_paise=?,status=CASE WHEN ?=0 THEN 'CONSUMED' ELSE 'PARTIAL' END,updated_at=? WHERE id=?",dbInt(z.availableQuantity),dbInt(value(z.availableQuantity,z.unitCost)),dbInt(z.availableQuantity),t,c.layerId),sql("INSERT INTO fifo_consumptions(id,fifo_layer_id,source_type,source_id,source_line_id,quantity_milliunits,rate_ten_thousandths,value_paise,created_at) VALUES(?,?,?,?,?,?,?,?,?)",ids.fifo_consumptions+ci++,c.layerId,"SALE",data.id,lid,dbInt(c.quantity),dbInt(c.rate),dbInt(c.value),t));}const avg=a.coveredCost*10_000_000n/l.q/100n;m.push(sql("INSERT INTO stock_ledger_entries(id,company_id,stock_book_id,item_id,entry_date,movement_type,transaction_type,transaction_id,reference_number,quantity_in_milliunits,quantity_out_milliunits,rate_ten_thousandths,value_paise,created_at,created_by_id) VALUES(?,?,?,?,?,'OUT','SALE',?,?,0,?,?,?,?,?)",ids.stock_ledger_entries+i,data.companyId,data.stockBookId,l.itemId,data.date,data.id,data.referenceNumber,dbInt(l.q),dbInt(avg),dbInt(a.coveredCost),t,userId),balance(data.companyId,data.stockBookId,l.itemId,-l.q,-a.coveredCost,t));}
 if(paid>total)throw new Error("Sale total cannot be less than the amount already received. Edit or delete the receipt first.");m.push(sql("UPDATE sales SET stock_book_id=?,customer_id=?,sale_type=?,invoice_number=?,invoice_date=?,due_date=?,subtotal_paise=?,gst_total_paise=?,grand_total_paise=?,fifo_cost_paise=?,gross_profit_paise=?,balance_amount_paise=?,payment_status=?,remarks=?,updated_at=?,updated_by_id=? WHERE id=?",data.stockBookId,data.customerId,data.documentType,data.referenceNumber,data.date,data.dueDate??null,dbInt(sub),dbInt(gst),dbInt(total),dbInt(cost),dbInt(sub-cost),dbInt(total-paid),pstatus(paid,total),data.remarks??null,t,userId,data.id),sql("UPDATE receivables SET stock_book_id=?,customer_id=?,document_number=?,document_date=?,due_date=?,transaction_type=?,total_amount_paise=?,balance_amount_paise=?,payment_status=?,remarks=?,updated_at=?,updated_by_id=? WHERE source_type='SALE' AND source_id=?",data.stockBookId,data.customerId,data.referenceNumber,data.date,data.dueDate??null,data.documentType,dbInt(total),dbInt(total-paid),pstatus(paid,total),data.remarks??null,t,userId,data.id));return{type:"Sale",id:data.id,before:old,mutations:m};
}

/** Retargets every consumption of a purchase layer to the new exact unit cost and
 * cascades derived sale/transfer ledger values. Quantity shrink below consumed is
 * rejected before mutation; therefore the complete plan is rollback-safe. */
export async function planPurchaseEdit(db:D1Database,data:PurchaseCommand,userId:number):Promise<EditPlan>{
 if(!data.id)throw new Error("Document ID is required.");const old=await db.prepare("SELECT * FROM purchases WHERE id=? AND is_void=0").bind(data.id).first<Row>();if(!old)throw new Error("Purchase was not found or is void.");const input=parse(data.lines,data.documentType==="GST"),ol=await rows(db,"SELECT pl.*,f.id layer_id,f.original_quantity_milliunits,f.available_quantity_milliunits FROM purchase_lines pl LEFT JOIN fifo_layers f ON f.source_type='PURCHASE' AND f.source_id=pl.purchase_id AND f.source_line_id=pl.id WHERE pl.purchase_id=? ORDER BY pl.id",data.id);if(ol.length!==input.length)throw new Error("Consumed purchase edits must preserve line count and identity.");const paid=BigInt(old.paid_amount_paise??0),t=ts(),m:SqlMutation[]=[];let sub=0n,gst=0n,total=0n;
 for(let i=0;i<input.length;i++){const l=input[i]!,o=ol[i]!,consumed=BigInt(o.original_quantity_milliunits!)-BigInt(o.available_quantity_milliunits!);if(l.q<consumed)throw new Error("Purchase quantity cannot be reduced below the quantity already consumed.");if(consumed>0n&&Number(o.item_id)!==l.itemId)throw new Error("A consumed purchase line cannot be changed to another item.");sub+=l.t.subtotal;gst+=l.t.gst;total+=l.t.total;const av=l.q-consumed,layer=Number(o.layer_id);m.push(sql("UPDATE purchase_lines SET item_id=?,quantity_milliunits=?,rate_ten_thousandths=?,gst_basis_points=?,subtotal_paise=?,gst_amount_paise=?,line_total_paise=? WHERE id=?",l.itemId,dbInt(l.q),dbInt(l.r),dbInt(l.g),dbInt(l.t.subtotal),dbInt(l.t.gst),dbInt(l.t.total),o.id),sql("UPDATE fifo_layers SET company_id=?,stock_book_id=?,item_id=?,source_reference=?,source_date=?,original_quantity_milliunits=?,available_quantity_milliunits=?,unit_cost_ten_thousandths=?,original_value_paise=?,available_value_paise=?,status=CASE WHEN ?=0 THEN 'CONSUMED' WHEN ?=? THEN 'OPEN' ELSE 'PARTIAL' END,updated_at=?,updated_by_id=? WHERE id=?",data.companyId,data.stockBookId,l.itemId,data.referenceNumber,data.date,dbInt(l.q),dbInt(av),dbInt(l.r),dbInt(value(l.q,l.r)),dbInt(value(av,l.r)),dbInt(av),dbInt(av),dbInt(l.q),t,userId,layer),sql("UPDATE fifo_consumptions SET rate_ten_thousandths=?,value_paise=(quantity_milliunits*?*100+5000000)/10000000 WHERE fifo_layer_id=?",dbInt(l.r),dbInt(l.r),layer),sql("UPDATE stock_ledger_entries SET company_id=?,stock_book_id=?,item_id=?,entry_date=?,reference_number=?,quantity_in_milliunits=?,rate_ten_thousandths=?,value_paise=? WHERE transaction_type='PURCHASE' AND transaction_id=? AND item_id=?",data.companyId,data.stockBookId,l.itemId,data.date,data.referenceNumber,dbInt(l.q),dbInt(l.r),dbInt(l.t.subtotal),data.id,o.item_id));}
 if(paid>total)throw new Error("Purchase total cannot be less than the amount already paid. Edit or delete the payment first.");m.push(sql("UPDATE sale_lines SET fifo_cost_paise=(SELECT COALESCE(SUM(value_paise),0) FROM fifo_consumptions WHERE source_type='SALE' AND source_line_id=sale_lines.id),gross_profit_paise=subtotal_paise-(SELECT COALESCE(SUM(value_paise),0) FROM fifo_consumptions WHERE source_type='SALE' AND source_line_id=sale_lines.id) WHERE id IN(SELECT source_line_id FROM fifo_consumptions c JOIN fifo_layers f ON f.id=c.fifo_layer_id WHERE f.source_type='PURCHASE' AND f.source_id=?)",data.id),sql("UPDATE sales SET fifo_cost_paise=(SELECT COALESCE(SUM(fifo_cost_paise),0) FROM sale_lines WHERE sale_id=sales.id),gross_profit_paise=subtotal_paise-(SELECT COALESCE(SUM(fifo_cost_paise),0) FROM sale_lines WHERE sale_id=sales.id) WHERE id IN(SELECT source_id FROM fifo_consumptions c JOIN fifo_layers f ON f.id=c.fifo_layer_id WHERE c.source_type='SALE' AND f.source_type='PURCHASE' AND f.source_id=?)",data.id),sql("UPDATE stock_ledger_entries SET rate_ten_thousandths=(SELECT CASE WHEN SUM(quantity_milliunits)=0 THEN 0 ELSE SUM(value_paise)*10000000/SUM(quantity_milliunits)/100 END FROM fifo_consumptions WHERE source_type=stock_ledger_entries.transaction_type AND source_id=stock_ledger_entries.transaction_id),value_paise=(SELECT COALESCE(SUM(value_paise),0) FROM fifo_consumptions WHERE source_type=stock_ledger_entries.transaction_type AND source_id=stock_ledger_entries.transaction_id) WHERE transaction_type IN('SALE','TRANSFER') AND transaction_id IN(SELECT source_id FROM fifo_consumptions c JOIN fifo_layers f ON f.id=c.fifo_layer_id WHERE f.source_type='PURCHASE' AND f.source_id=?)",data.id),sql("UPDATE purchases SET company_id=?,stock_book_id=?,supplier_id=?,purchase_type=?,bill_number=?,bill_date=?,due_date=?,subtotal_paise=?,gst_total_paise=?,grand_total_paise=?,balance_amount_paise=?,payment_status=?,remarks=?,updated_at=?,updated_by_id=? WHERE id=?",data.companyId,data.stockBookId,data.supplierId,data.documentType,data.referenceNumber,data.date,data.dueDate??null,dbInt(sub),dbInt(gst),dbInt(total),dbInt(total-paid),pstatus(paid,total),data.remarks??null,t,userId,data.id),sql("UPDATE payables SET stock_book_id=?,supplier_id=?,document_number=?,document_date=?,due_date=?,transaction_type=?,total_amount_paise=?,balance_amount_paise=?,payment_status=?,remarks=?,updated_at=?,updated_by_id=? WHERE source_type='PURCHASE' AND source_id=?",data.stockBookId,data.supplierId,data.referenceNumber,data.date,data.dueDate??null,data.documentType,dbInt(total),dbInt(total-paid),pstatus(paid,total),data.remarks??null,t,userId,data.id));return{type:"Purchase",id:data.id,before:old,mutations:m};
}
